name = "veritas-radix"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "service-worker"

[[pages_build_output_dir]]
value = "dist"

[env.production.vars]
VITE_API_URL = "https://veritas-radix-backend-production.up.railway.app"
VITE_FRONTEND_URL = "https://veritas-radix.pages.dev"
NODE_ENV = "production"

[env.preview.vars]
VITE_API_URL = "https://veritas-radix-backend-production.up.railway.app"
VITE_FRONTEND_URL = "https://veritas-radix.pages.dev"
NODE_ENV = "development"