name = "veritas-radix-test"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production.vars]
VITE_API_URL = "https://veritas-radix-test-1.onrender.com"
NODE_ENV = "production"

[env.preview.vars]
VITE_API_URL = "https://veritas-radix-test-1.onrender.com"
NODE_ENV = "development"