[phases.setup]
nixPkgs = ["python39", "nodejs", "yarn"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn veritas_radix.wsgi:application --bind 0.0.0.0:$PORT"