[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DEBUG = "False"
DJANGO_SETTINGS_MODULE = "veritas_radix.settings"
PYTHONPATH = "/app"
PORT = "8000"